openedx/openedx-learning

docs/decisions/0003-content-extensibility.rst

Outline our approach for third-party apps to extend Learning Core data models.

docs: add ADR for content extensibility

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/quality.txt
requirements/test.txt

The version of pip-tools that was previously pinned breaks
with the latest version of pip.

chore: run make upgrade

---

.importlinter
requirements/base.in
requirements/base.txt
requirements/ci.in
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

I've combined two commits into one PR because they both update dependencies:
```
feat: add import linting
import-linter is meant to help us keep our internal dependencies clear,
and prevent accidental circular dependencies or other unwanted code
relationships.
You can run the linter with the command: lint-imports
```
```
chore: remove unnecessary dependencies
The standards cookiecutter for Open edX projects includes
django-model-utils and django-simple-history. This repo doesn't really
need them because:
1. django-model-utils is only really used for TimeStampedModel, and that
is just to get consistent naming of created/modified fields. We can
do that without taking on the entire dependency.
2. django-simple-history offers a convenient way to make a history
table, and we do have versioned …
```

Remove dependencies, add import-linting

---

docs/decisions/0004-content-tagging.rst

This PR adds an ADR to define where the new tagging service will live.
**Reference issue:** https://github.com/openedx/modular-learning/issues/43.
**Internal OpenCraft ticket:** [FAL-3373](https://tasks.opencraft.com/browse/FAL-3373).

docs: ADR for tagging service.

---

docs/decisions/0012-system-taxonomy-creation.rst
docs/decisions/0013-system-taxonomy-auto-tagging.rst

This PR documents the decisions that arose from https://github.com/openedx/modular-learning/issues/61
The ADRs here continues the enumeration of https://github.com/openedx/openedx-learning/pull/55
**Testing instructions**
- Check the added ADRs for clarity and correctness.
**Supporting information**
Closes https://github.com/openedx/modular-learning/issues/61

System-defined taxonomies architecture decisions

---

docs/decisions/0013-system-taxonomy-auto-tagging.rst

Documenting the decision to move from using `openedx-filters` to `openedx-events`

feat: update automatic tagging decision

---

openedx_learning/core/contents/migrations/0001_initial.py

AWS Aurora does not support COMPRESSED in its MySQL implementation:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Migrating.RDSMySQL.Import.html
As requested by @ormsbee : https://github.com/openedx/openedx-learning/pull/65#issuecomment-1643019023

fix: removes COMPRESSED row format from openedx_learning core

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml
tox.ini

Creates pypi-publish.yml using the [procedure recommended by edx-platform](https://github.com/openedx/edx-platform/blob/83f54aeebe5a729935fe7de10c56bccd63c1b228/requirements/edx/github.in#L15-L19).

build: publish openedx-learning to pypi

---

openedx_tagging/core/tagging/rest_api/urls.py
openedx_tagging/core/tagging/rest_api/v1/permissions.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/urls.py
openedx_tagging/core/tagging/rest_api/v1/views.py
openedx_tagging/core/tagging/rules.py
openedx_tagging/core/tagging/urls.py
projects/urls.py
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.in
requirements/test.txt
test_settings.py
tests/openedx_tagging/core/tagging/test_rules.py
tests/openedx_tagging/core/tagging/test_views.py
tox.ini

This PR adds support for creating, viewing, updating and deleting Taxonomies via REST APIs, with the permissions applied accordingly.
* Closes https://github.com/openedx/modular-learning/issues/73
* Ensure that all endpoints in the related issue are implemented.
* Ensure that the tests cover the expected behaviour of the view and permissions as described in the related issue.

Taxonomy view/management REST APIs

---

mypy.ini

Quick fix to remove a comment that I left in by accident after copy-pasting. It doesn't make any sense in the new context.

Remove a comment copy-pasta

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/models/base.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
openedx_tagging/core/tagging/rules.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_rules.py
tests/openedx_tagging/core/tagging/test_views.py

This PR implements the tagging REST API for updating object tags.
* Closes https://github.com/openedx/modular-learning/issues/82
* Ensure that the tests cover the expected behavior of the view as described in the related issue.
____
Private-ref: [FAL-3474](https://tasks.opencraft.com/browse/FAL-3474)

feat: implement tagging rest api tag object [FC-0030]

---

docs/decisions/0014-single-taxonomy-view-api.rst

This PR adds an ADR to define the representation of the tags and the pagination in the single taxonomy view api
Reference issue: https://github.com/openedx/modular-learning/issues/75

docs: ADR for pagination and repr of single taxonomy view api [FC-0030]

---

docs/decisions/0014-single-taxonomy-view-api.rst
openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/import_export/import_plan.py
openedx_tagging/core/tagging/import_export/parsers.py
openedx_tagging/core/tagging/migrations/0007_tag_import_task_log_null_fix.py
openedx_tagging/core/tagging/migrations/0008_taxonomy_description_not_null.py
openedx_tagging/core/tagging/models/base.py
openedx_tagging/core/tagging/models/system_defined.py
openedx_tagging/core/tagging/rest_api/paginators.py
openedx_tagging/core/tagging/rest_api/v1/permissions.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/urls.py
openedx_tagging/core/tagging/rest_api/v1/views.py
openedx_tagging/core/tagging/rules.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py

Adds a new view to return tags for a given taxonomy. With this view, you can:
- Return paginated root tags.
- Return paginated children of given tag.
- Search tags in all taxonomy.
- Search tags on a children list.
Also updates the ADR 0014 with some logics on search.
- Closes https://github.com/openedx/modular-learning/issues/75
- Ensure that the tests cover the expected behavior of the view as described in the related issue.
- Run this command to create a small taxonomy:
```
python manage.py loaddata tests/openedx_tagging/core/fixtures/tagging.yaml
```
- Run this commands to create a large taxonomy:
```
python manage.py shell
> from tests.openedx_tagging.core.tagging.test_views import TestTaxonomyTagsView
> case = TestTaxonomyTagsView()
> case.setUp()
> case.build_large_taxonomy()
> …
```

Single taxonomy view [FC-0030]

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/models/base.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py

This PR enforces a 100 hardcoded limit on the number of ObjectTags applied on any object. It also removes the pagination of the tagging REST API for listing and updating object tags.
* Closes https://github.com/openedx/modular-learning/issues/99
* Please ensure that the tests cover the expected behavior of the view as described in the related issue.
____
Private-ref: [FAL-3501](https://tasks.opencraft.com/browse/FAL-3501)

Enforce limit on number of tags per object

---

openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/utils.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_views.py

**Changes added:**
* Authentication classes added to tagging API views. This is so that calls from the MFE are correctly authenticated
* Cast taxonomies before serialize in TaxonomySerializer
* Test updated
**Testing instructions**
- Verify that the behaviour of the tests is unchanged
- Test this changes on https://github.com/openedx/edx-platform/pull/33439 and https://github.com/openedx/frontend-app-course-authoring/pull/622
**After merge**
- Bump a version
**Internal ticket:** [FAL-3522](https://tasks.opencraft.com/browse/FAL-3522)
**Github issue:** https://github.com/openedx/modular-learning/issues/104

feat: Changes to build Taxonomy List page [FC-0036]

---

openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
openedx_tagging/core/tagging/rules.py
tests/openedx_tagging/core/tagging/test_views.py

Add a new action to allow exporting a single Taxonomy
- https://github.com/openedx/modular-learning/issues/113
1. Please ensure that the tests cover the expected behavior of the view
2.  Using this branch, run the dev server: `python manage.py runserver`
3. Create a superuser using `python manage.py createsuperuser`
5. Login in admin and authenticate with the user created (http://127.0.0.1:8000/admin)
6. In the same browser session, check the result in the API Viewer:
- http://127.0.0.1:8000/tagging/rest_api/v1/taxonomies/-1/export/?output_format=csv
- http://127.0.0.1:8000/tagging/rest_api/v1/taxonomies/-1/export/?output_format=json
7. In the same browser session, check if the API also downloads the file with the correct filename:
- …

feat: add export taxonomy rest api

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/models/base.py
openedx_tagging/core/tagging/rest_api/v1/permissions.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
openedx_tagging/core/tagging/rules.py
tests/openedx_tagging/core/tagging/test_rules.py
tests/openedx_tagging/core/tagging/test_views.py

This PR introduces the CRUD python and REST APIs for interacting with Taxonomy Tags. Creating, updating and deleting them.
Related Tickets:
- Closes https://github.com/openedx/modular-learning/issues/136
Make sure all the tests pass, and they cover all the cases.
---
Private-ref: [FAL-3519](https://tasks.opencraft.com/browse/FAL-3519)

feat: CRUD API for Taxonomy Tags [FC-0036]

---

openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_views.py

Configure the `lookup_value_regex` in the TaxonomyView. Currently, accessing the API using an invalid pk (i.e. using a `str`) throws an exception when the value is converted to `int`, returning status `500`, instead of a `404`.
1. Please ensure that the tests cover the expected behavior of the view
2.  Using this branch, run the dev server: `python manage.py runserver`
3. Create a superuser using `python manage.py createsuperuser`
5. Login in admin and authenticate with the user created (http://127.0.0.1:8000/admin)
6. In the same browser session, check the result in the API Viewer:
- http://127.0.0.1:8000/tagging/rest_api/v1/taxonomies/invalid_pk (should return 404)
____
Private-ref: [FAL-3529](https://tasks.opencraft.com/browse/FAL-3529)

fix: add `lookup_value_regex` for taxonomy rest api

---

mysql_test_settings.py
openedx_learning/__init__.py
openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/data.py
openedx_tagging/core/tagging/import_export/parsers.py
openedx_tagging/core/tagging/models/base.py
openedx_tagging/core/tagging/models/system_defined.py
openedx_tagging/core/tagging/models/utils.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/fixtures/tagging.yaml
tests/openedx_tagging/core/tagging/import_export/test_template.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py
tests/openedx_tagging/core/tagging/utils.py
tox.ini

This proposal for the Tagging API combines the implementations of `get_tags()`, `get_filtered_tags()`, and `autocomplete_tags()` into a single `Taxonomy.get_filtered_tags()` method that can implement every type of pagination and search that I'm aware we'll need.
It:
* Provides a single API that works with static, dynamic, and free text taxonomies (dynamic means like language or user)
* Can be used to list all the tags in the taxonomy hierarchically, get a flat paginated list of all the tags below a certain parent, search for tags that match a keyword and return their lineage too, and more.
* Uses a fixed number of queries, generally one or two
* Returns a `QuerySet` so it supports any type of pagination or iteration over the whole set
* [Can return all the tags in a taxonomy up to the max …

Tagging: More powerful, flexible implementation of get_filtered_tags() [FC-0036]

---

openedx_tagging/core/tagging/import_export/api.py
tests/openedx_tagging/core/tagging/import_export/test_api.py

Small fix to allow api calls to EXPORT taxonomies with `system_defined=True` and `allow_free_text=True`.
The IMPORT restrictions where not changed.
___
Private-ref: [FAL-3528](https://tasks.opencraft.com/browse/FAL-3528)

fix: allow export of system defined and open taxonomies

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py

This PR:
1. Makes the `get_object_tag_counts` API available via python as well as REST. Previously it was REST-only.
2. Makes the `get_object_tags` and `get_object_tag_counts` APIs ignore tags from deleted or disabled taxonomies by default. Anything else would be confusing for users. Keep in mind, we do preserve the underlying ObjectTag data; we just don't want to display it.
This is for https://github.com/openedx/modular-learning/issues/118 part 1b.
Private ref: [FAL-3564](https://tasks.opencraft.com/browse/FAL-3564).

Python API to get tag counts, ignore deleted/disabled ObjectTags by default [FC-0036]

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_views.py

Changes the import endpoint to overwrite previous tags from the target taxonomy
* Part of https://github.com/openedx/modular-learning/issues/140
* Please ensure that the tests cover the expected behavior of the view
____
Private-ref: [FAL-3536](https://tasks.opencraft.com/browse/FAL-3536)

fix: overwrite previous tags on import

---

openedx_tagging/core/tagging/import_export/api.py
openedx_tagging/core/tagging/import_export/parsers.py

* The import code that accepts a file object should have type `BinaryIO` (any file-like object that produces bytes), not `BytesIO` (specifically an in-memory bytes object and not a file handle)
* As I experienced, if a `TypeError` occurred during import (e.g. because you forgot to open the CSV file as binary instead of as a string...) then the import task would become permanently stuck because `TypeError` exceptions were not caught.
No need for a version bump with this fix.
Private ref: can be considered part of FAL-3531.

Very minor fixes for import code [FC-0036]

---

docs/decisions/0014-single-taxonomy-view-api.rst
openedx_learning/__init__.py
openedx_tagging/core/tagging/models/base.py
openedx_tagging/core/tagging/rest_api/paginators.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py

This change fixes some bugs and inconsistencies in the "get tags" REST API. Hopefully it will be much easier to understand and use now.
Bugs:
* Before, the pagination and tree depth behavior of the function would be different depending on whether a search term was used or not.
* Before, by default, the pagination format and depth of the results would depend on the overall size of the taxonomy, which could produce unexpected results for API consumers who aren't aware of this.
* Before, the pagination would sometimes put a child on a different page than its parent, which was not incorrect but could be confusing.
* When using a search term and loading sub tags using "sub_tags_url", the search term filter would be lost and all children would be returned, even if they didn't match the search. …

fix: Fix bugs in the "get tags" REST API, make it more consistent [FAL-3530] [FC-0036]

---

openedx_tagging/core/tagging/import_export/actions.py
openedx_tagging/core/tagging/import_export/import_plan.py
tests/openedx_tagging/core/tagging/import_export/test_api.py
tests/openedx_tagging/core/tagging/import_export/test_import_plan.py

This PR prevents creating an `UpdateParent` action associated with a Tag that will be deleted.
Example:
```
- Tag 1
- Tag 1.1
- Tag 1.1.1
```
Actions before PR:
```
#1 Delete Tag 1
#2 Delete Tag 1.1
#3 Delete Tag 1.1.1
#4 Update parent tag of Tag 1.1 from Tag 1 to None (** THIS FAILS BECAUSE Tag 1.1 WAS DELETED **)
#5 Update parent tag of Tag 1.1.1 from Tag 1.1 to None  (** THIS FAILS BECAUSE Tag 1.1.1 WAS DELETED **)
```
Actions after PR:
```
#1 Delete Tag 1
#2 Delete Tag 1.1
#3 Delete Tag 1.1.1
```
It also checks if the Tag actually exists in the database before executing the `Delete` action. In the example above, because we didn't update the parent of tags 1.1 and 1.1.1, actions `#2` and `#3` should be skipped because both tags were cascade deleted on action `#1`.
* Please ensure that …

 fix: skip parent update from deleted tags 

---

docs/decisions/0015-serving-static-assets.rst

A first stab at an asset serving ADR that could serve Studio and the LMS. I'm especially looking for feedback on how we could do the cookie auth handoff (or for someone to tell me why it's a terrible idea).

docs: ADR for serving static assets

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/import_export/api.py
openedx_tagging/core/tagging/import_export/tasks.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/import_export/test_api.py
tests/openedx_tagging/core/tagging/import_export/test_tasks.py
tests/openedx_tagging/core/tagging/import_export/test_template.py
tests/openedx_tagging/core/tagging/test_views.py

This PR adds a `plan_only` param to the API and creates a new REST endpoint to allow the frontend to query for an import plan without actually importing anything.
Part of:
- https://github.com/openedx/modular-learning/issues/126
* Please ensure that the tests cover the expected behavior
____
Private-ref:
- [FAL-3539](https://tasks.opencraft.com/browse/FAL-3539)

feat: add plan_only param to api and create /tags/import/plan endpoint [FC-0036]

---

openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/models/utils.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_views.py

This updates our "get tag counts" API so that the tag counts can include the implicit tags.
Currently, we have an inconsistency in how the counts are displayed in the platform:
This API change will allow us to make the counts in both places include the implicit tags (use the higher number consistently).
Private ref: FAL-3573

feat: Count implicit tags

---

openedx_tagging/core/tagging/import_export/actions.py
openedx_tagging/core/tagging/import_export/import_plan.py
tests/openedx_tagging/core/tagging/import_export/test_api.py
tests/openedx_tagging/core/tagging/import_export/test_import_plan.py
tests/openedx_tagging/core/tagging/test_views.py

If we try to import tags over a taxonomy that shares the same Tag Value, an error is thrown about the conflict tag value.
It can be reproduced by importing the Template Taxonomy over the "Lightcast Open Skills Taxonomy".
Both taxonomies have a tag with the value "piano". In the plan, it tries to create the tag piano for the Template before deleting the one from Lightcast, raising an error.
This PR changes the order of the import actions, always running the DeleteTag actions before others to avoid this.
Please ensure that the tests cover the expected behavior.
---
Private-ref:
- [FAL-3603](https://tasks.opencraft.com/browse/FAL-3603)

fix: bug importing tags with the same value as an existing one

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/import_export/actions.py
openedx_tagging/core/tagging/import_export/import_plan.py
openedx_tagging/core/tagging/models/base.py
tests/openedx_tagging/core/tagging/import_export/test_actions.py
tests/openedx_tagging/core/tagging/import_export/test_api.py
tests/openedx_tagging/core/tagging/import_export/test_import_plan.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py

This fix an error when it comes to performing actions on a taxonomy with tags that have `external_id=None`
Part of: https://github.com/openedx/modular-learning/issues/126
Please ensure that the tests cover the expected behavior

fix: Issue when delete all tags on import [FC-0036]

---

openedx_learning/__init__.py
openedx_learning/core/components/api.py
tests/openedx_learning/core/components/test_api.py

Also bumps the version to 0.6.1.
```
fix: map PublishableEntity keys to library conventions
PublishableEntities have their own "key" field that must be unique
within a LearningPackage. Components are PublishableEntities (via 1:1
relationship), but they store that data as separate fields that are
useful for filtering and grouping on. When we create a Component, it
creates a PublishableEntity key value based on its own namespace, type,
and local key.
Before this commit, we followed a more ModuleStore-like convention and
the derived key would have its type and local key separated by "@":
xblock.v1:html@424337d3-e1fc-4970-822a-684b1ccb0c1d
This commit changes it so that we follow the v2 libraries convention of
having a ":" between the two instead: …
```

Change PublishableEntity key convention to match v2 lib conventions (v 0.6.1)

---

openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_api.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_system_defined_models.py

This PR changes the param order in the `tag_content` function and the tests accordingly.
PS: all function calls at `edx-platform` use named parameters, so this PR doesn't impact there.
* Please ensure that the tests cover the expected behavior
___
Private ref: [FAL-3621](https://tasks.opencraft.com/browse/FAL-3621)

refactor: tag_object param order

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/models/base.py
tests/openedx_tagging/core/tagging/test_api.py

This PR adds a `get_taxonomy_by_export_id` method. This method will be used in to import taxonomy data.
- Part of: https://github.com/openedx/modular-learning/issues/180
- Please ensure that the tests cover the expected behavior
___
Private ref: [FAL-3621](https://tasks.opencraft.com/browse/FAL-3621)

feat: add get_taxonomy_by_export_id method [FC-0049]

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_models.py
tests/openedx_tagging/core/tagging/test_views.py

Updates ObjectTagView Put request to update multiple taxonomies in one request
- Github issue: https://github.com/openedx/modular-learning/issues/190
- Related PRs:
- https://github.com/openedx/frontend-app-course-authoring/pull/939
- https://github.com/openedx/edx-platform/pull/34490
- Internal ticket: [FAL-3645](https://tasks.opencraft.com/browse/FAL-3645)
- Follow the testing instructions of https://github.com/openedx/frontend-app-course-authoring/pull/939

[FC-0036] feat: Update ObjectTagView

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_views.py

This changes the import taxonomy view to allow users to import a taxonomy without specifying an export id. If it is provided it will use it otherwise, it will generate one.
Related Tickets:
- Needed for: https://github.com/openedx/frontend-app-course-authoring/pull/955
1. Follow the testing instructions in https://github.com/openedx/frontend-app-course-authoring/pull/955
1. Confirm the tests cover this condition
---
Private-ref: [FAL-3706](https://tasks.opencraft.com/browse/FAL-3706)

[FC-0049] feat: Auto generate taxonomy export ID if not provided

---

docs/decisions/0016-python-public-api-conventions.rst

This proposes refactoring our apps and introducing two major new conventions at the same time:
1. Apps in ``openedx_learning.core`` would now be in ``openedx_learning.apps.authoring``, setting a pattern for grouping apps together into larger package groups.
2. A new ``openedx_learning.api.authoring`` module would be created to aggregate API modules from apps in ``openedx_learning.apps.authoring``.
I originally wrote this up as a part of the major refactoring in #184, but separated out here so that we can discuss it in its own space.

ADR for Public Python API Conventions

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rules.py
tests/openedx_tagging/core/tagging/test_views.py

This updates rules to add `can_remove_object_tag_objectid` to Objet tag views
- Github issue: https://github.com/openedx/modular-learning/issues/204
- Internal ticket: [FAL-3720](https://tasks.opencraft.com/browse/FAL-3720)
- Follow the testing instructions in https://github.com/openedx/frontend-app-course-authoring/pull/987

[FC-0049] feat: Update permissions to remove object tags

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/import_export/actions.py
openedx_tagging/core/tagging/import_export/api.py
openedx_tagging/core/tagging/import_export/import_plan.py
openedx_tagging/core/tagging/models/import_export.py

* Adds time elapsed to import log.
* Fix issues with memory and time when importing a large taxonomy.
- Github issue: https://github.com/openedx/modular-learning/issues/213
- Related to: https://github.com/openedx/edx-platform/pull/34796
- Internal ticket: https://tasks.opencraft.com/browse/FAL-3721
It has been tested with taxonomies that take too long or could not finish due to a memory backup. These are their average times after fixing the issue:
- `WGU Instructional Design: K-12 Collection`: 5.95 seconds.
- `FlatTaxonomy`: 65.55 seconds.
- `Lightcast Open Skills Taxonomy`: 76.5 seconds.
- Use this branch of `edx-platform`: https://github.com/openedx/edx-platform/pull/34796
- Run `make requirements` on cms-shell
- Ensure you have the testing data: …

[FC-0049] fix: Issues when importing a large taxonomy

---

openedx_learning/apps/authoring/publishing/api.py
tests/openedx_learning/apps/authoring/publishing/test_api.py

Details are in a comment from this change:
```python
```

fix: prevent soft-deletes from being re-published every time

---

openedx_learning/apps/authoring/publishing/api.py
tests/openedx_learning/apps/authoring/publishing/test_api.py

Related PRs and issues: 
* https://github.com/openedx/edx-platform/pull/35243
* ~https://github.com/open-craft/frontend-app-course-authoring/pull/58~ https://github.com/openedx/frontend-app-course-authoring/pull/1214
* https://github.com/openedx/frontend-app-course-authoring/issues/1200

feat: option to include deleted drafts while fetching unpublished entities [FC-0062]

---

openedx_learning/lib/collations.py

Setting the collation via Field db_parameters was not properly supported before Django 4.x. We worked around this with a Django 3.2-compatible hack in https://github.com/ormsbee/openedx-learning/commit/084ec21a0292584f42f79930b6d6fe3bcf0ef08b. Now that we require at least Django 4.2, we no longer need the compatibility hack.

Remove Django 3.2 collations compatibility hack

---

openedx_learning/api/authoring.py
openedx_learning/apps/authoring/components/api.py
tests/openedx_learning/apps/authoring/components/test_api.py

Since the authoring apps now have their APIs aggregated into the public `openedx_learning.api.authoring` module, `create_next_version` will be ambiguous as soon as we create other versioned things like Units.
I'm including an alias to give more flexibility for switching edx-platform over.

refactor: create_next_version -> create_next_component_version

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/collections/api.py
tests/openedx_learning/apps/authoring/collections/test_api.py

Adds `get_collections` api for https://github.com/openedx/edx-platform/pull/35324

feat: add get_collections api

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/publishing/model_mixins.py

This PR exposes the `create_by` field in `PublishableEntityMixin` to facilitate it's use.
- https://github.com/openedx/edx-platform/pull/35476#discussion_r1757815110
Part of:
- https://github.com/openedx/frontend-app-course-authoring/issues/1190
Check https://github.com/openedx/frontend-app-course-authoring/pull/1275
___
Private ref: [FAL-3802](https://tasks.opencraft.com/browse/FAL-3802)

feat: expose create_by field in PublishableEntityMixin [FC-0062]

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/components/api.py
openedx_learning/apps/authoring/components/management/commands/add_assets_to_component.py
openedx_learning/apps/authoring/contents/api.py
openedx_learning/apps/authoring/contents/models.py
openedx_learning/apps/authoring/publishing/model_mixins.py
tests/openedx_learning/apps/authoring/components/test_assets.py
tests/openedx_learning/apps/authoring/components/test_models.py

Low-level Learning Core API calls for returning references to content associated with a Component. Uses `X-Accel-Redirect`.
```
This adds a number of API calls to the Authoring public API in order to
support associating static assets with Components and allowing them to
be downloaded.
Added:
* get_component_by_uuid
* get_component_version_by_uuid
* get_content_info_headers
* get_redirect_response_for_component_asset
Modified:
* create_next_component_version - made title optional
* create_component_version_content - annotation for learner_downloadable
Most of the justification for this approach can be found in the
docstring for get_redirect_response_for_component_asset.
Note that there is currently no backend redis/memcached caching of the
ComponentVersion and Content information. This …
```

Basic asset response support

---

.importlinter

All new apps should have an entry in the .importlinter config file so that our internal dependency tree stays clean, but we don't actually document that anywhere yet.
Made https://github.com/openedx/openedx-learning/issues/230 to track work around making a "new app" checklist doc to help with this sort of thing in the future.

test: add collections app to import linter config

---

Makefile
openedx_learning/__init__.py
openedx_learning/apps/authoring/collections/admin.py
openedx_learning/apps/authoring/collections/api.py
openedx_learning/apps/authoring/components/api.py
tests/openedx_learning/apps/authoring/collections/test_api.py

Adds API methods for soft-deleting, hard-deleting and restoring Collections, and a Django Admin screen to allow superusers to hard delete any soft-deleted collections.
Also adds a convenience method `get_collection_components`, which makes it easier for ContentLibraries to interact with collection entities.
Related to: https://github.com/openedx/modular-learning/issues/231
Private-ref: [FAL-3809](https://tasks.opencraft.com/browse/FAL-3809)
1. Using the API, create a couple collections (`python manage.py shell`):
```python
from openedx_learning.authoring import api
learning_package = api.create_learning_package("FAL-3809", "Learning package for FAL-3809")
api.create_collection(learning_package.id, "FAL-3809-1", title="Collection 1 for FAL-3809")
api.create_collection(learning_package.id, …
```

Collections Django Admin + soft delete, hard delete, and restore

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/components/admin.py
openedx_learning/apps/authoring/components/api.py
openedx_learning/apps/authoring/contents/admin.py
openedx_learning/apps/authoring/contents/models.py
test_settings.py
tests/openedx_learning/apps/authoring/components/test_api.py
tests/openedx_learning/apps/authoring/components/test_assets.py
tests/openedx_learning/apps/authoring/contents/test_file_storage.py

I think this should be the last of the Learning Core changes needed to get minimal asset handling into Content Libraries.
The meat of this is:
```
feat!: require OPENEDX_LEARNING setting for Content storage
WARNING: This commit will break any file-backed Content entries you
currently have. Though you will likely only have them if you've used the
very recently created add_assets_to_component command.
This commit switches us away from using the default_storage and requires
the project to set an OPENEDX_LEARNING settings dictionary with a MEDIA
key like:
OPENEDX_LEARNING = {
'MEDIA': {
"BACKEND": "django.core.files.storage.FileSystemStorage",
"OPTIONS": {
"location": "/openedx/media-private/openedx-learning",
}
}
}
If no such setting is present, Content operations that require file
access …
```

Asset handling updates (config, admin)

---

openedx_learning/apps/authoring/components/api.py
tests/openedx_learning/apps/authoring/components/test_api.py

Adds api for updating collections for a given component. See https://github.com/openedx/frontend-app-authoring/pull/1373 for more information.

feat: component set collection api [FC-0062]

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/contents/models.py

Admin page calls `contents.os_path()`, and if the storage backend doesn't support `path`, we can't load the admin page for that asset.
See e.g https://tagging-preview.staging.do.opencraft.hosting/admin/oel_contents/content/225/change/ 
<details><summary>Traceback:</summary>
```
2024-10-24 05:36:25,936 ERROR 15 [django.request] [user 20] [ip 180.150.117.27] log.py:241 - Internal Server Error: /admin/oel_contents/content/225/change/
Traceback (most recent call last):
File "/openedx/venv/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
return self.fields_map[field_name]
~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'os_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

Fix minor asset storage admin issue [FC-0062]

---

.coveragerc
openedx_learning/__init__.py
openedx_learning/apps/authoring/components/api.py
openedx_learning/apps/authoring/components/management/commands/add_assets_to_component.py
tests/openedx_learning/apps/authoring/components/test_api.py

This PR updates `create_next_component_version` to handle raw bytes and content.pk logic to add assets. Closes https://github.com/openedx/openedx-learning/issues/241

feat: handle file content logic when creating next component version

---

openedx_learning/apps/authoring/contents/models.py

Closes: https://github.com/openedx/openedx-learning/issues/152

chore: remove unnecessary type checking

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/rest_api/v1/views.py
tests/openedx_tagging/core/tagging/test_views.py

**Current:**
The current approach is to save the id of the content through a generic string, so that the tag can be linked to any type of content, no matter what type of ID have. For example, with this approach we can link standalone blocks and library blocks, both on Denver (v3) and Blockstore Content Libraries (v2).
**Issue:**
With complex object_id e.g; `course-v1:MIT+lt101.1+101.1` which is a acceptable format, django resolver is throwing 404
**What this PR does?**
This PR is adding a regex for `object_id` lookup field value in `ObjectTagView` and `ObjectTagCountsView` to make it accept special characters specially those which are common in openedx course creation
Before:
After:

fix: Update ObjectTagView and ObjectTagCountsView to accept complex objectIds

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/rest_api/v1/serializers.py
openedx_tagging/core/tagging/rest_api/v1/views.py

This PR fixes two errors seen during the automatic Swagger API docs generation.
Part of: https://github.com/openedx/openedx-learning/issues/272
Private-ref: [FAL-4039](https://tasks.opencraft.com/browse/FAL-4039)
1. Install this branch in your edx-platform devstack
2. Visit the Studio API docs page, e.g http://local.openedx.io:8001/api-docs/
Note that the page renders now without error.

fix: errors during swagger api-docs generation

---

openedx_learning/__init__.py
openedx_tagging/core/tagging/api.py
tests/openedx_tagging/core/fixtures/tagging.yaml
tests/openedx_tagging/core/tagging/test_api.py

Adds a `unmark_copied_tags` method to the tagging API which unsets the `is_copied` flag on the given object's tags.
Part of: https://github.com/openedx/modular-learning/issues/244
Private-ref: [FAL-4008](https://tasks.opencraft.com/browse/FAL-4008)
See edx-platform PR.

feat: adds unmark_copied_tags method to tagging API [FC-0076]

---

openedx_learning/apps/authoring/components/api.py
openedx_learning/apps/authoring/components/apps.py
openedx_learning/apps/authoring/components/models.py
openedx_learning/apps/authoring/contents/models.py
openedx_learning/apps/authoring/publishing/model_mixins.py
openedx_learning/apps/authoring/publishing/models.py
openedx_learning/contrib/media_server/apps.py
openedx_learning/lib/validators.py
openedx_tagging/core/tagging/api.py
openedx_tagging/core/tagging/rest_api/v1/permissions.py
openedx_tagging/core/tagging/rules.py
tests/openedx_learning/apps/authoring/collections/test_api.py
tests/openedx_learning/apps/authoring/components/test_api.py
tests/openedx_tagging/core/tagging/test_views.py

Added type annotations so that mypy checks more code. If a function doesn't have any type annotations at all, mypy will ignore it completely.
Django-rules now has types, so we don't need `# type: ignore[import]` on it.
Private ref: part of FAL-4051

Minor typing improvements [FC-0083]

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/publishing/api.py
openedx_learning/apps/authoring/publishing/models/entity_list.py
openedx_learning/apps/authoring/units/api.py
tests/openedx_learning/apps/authoring/units/test_api.py

**Description:**
Updates `create_next_container_version` api to handle addition or removal of children entities.
**Related to:** https://github.com/openedx/frontend-app-authoring/issues/1706 and https://github.com/openedx/frontend-app-authoring/issues/1705
`Private-ref`: https://tasks.opencraft.com/browse/FAL-4109
**Test instructions:**
* Read code
* Verify that tests are passing

feat: api for updating children in container [FC-0083]

---

openedx_learning/apps/authoring/publishing/api.py
tests/openedx_learning/apps/authoring/units/test_api.py

Fix for https://github.com/openedx/openedx-learning/issues/303

fix: get_containers_with_entity() was returning duplicate results

---

openedx_learning/apps/authoring/sections/api.py
openedx_learning/apps/authoring/subsections/api.py
openedx_learning/apps/authoring/units/api.py

* Remove duplicated `get_subsections_in_section` in `__all__`
* Remove duplicated `get_units_in_subsection` in `__all__`
* Remove duplicated `get_components_in_unit` in `__all__`
This change does not affect functionality, it is just a cleanup in the code.

style: Delete duplicated code in units, subsections and sections APIs

---

tests/openedx_learning/apps/authoring/components/test_models.py
tests/openedx_learning/apps/authoring/publishing/test_models.py

This PR makes some simplifications to `PublishableEntityMixin` and `PublishableEntityVersionMixin` so that their subclasses like `ComponentVersion` automatically get the correct type on their `objects` class property, and don't have to override it to satisfy mypy. This will slightly simplify the code as we get more publishable entities in the near future (e.g. components and units).
I also got rid of the custom `PublishableEntityMixinManager` and `PublishableEntityVersionMixinManager` classes, replacing them with the reusable `WithRelationsManager` that does the same thing and which now supports generic typing properly.
New type-only tests are added to assert that the typing of the manager (`objects`) and its returned instances are correct.

test: verify correct typing of mixins

---

.importlinter
openedx_learning/apps/authoring/backup_restore/admin.py
openedx_learning/apps/authoring/backup_restore/api.py
openedx_learning/apps/authoring/backup_restore/apps.py
openedx_learning/apps/authoring/backup_restore/constants.py
openedx_learning/apps/authoring/backup_restore/management/commands/lp_dump.py
openedx_learning/apps/authoring/backup_restore/models.py
openedx_learning/apps/authoring/backup_restore/toml.py
openedx_learning/apps/authoring/backup_restore/utils.py
projects/dev.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

Fixes: https://github.com/openedx/openedx-learning/issues/331
These changes are the first step toward implementing a dump/load format for libraries. This initial approach introduces a minimal `lp_dump` management command for Learning Core.
The contents of `package.toml` are shown below
App requirements:
In terms of the output of the `lp_dump` command itself:

feat: lp_dump management command added

---

openedx_learning/apps/authoring/backup_restore/api.py
openedx_learning/apps/authoring/backup_restore/management/commands/lp_dump.py
openedx_learning/apps/authoring/backup_restore/toml.py

Fixes: https://github.com/openedx/openedx-learning/issues/337
This PR updates the `lp_dump` management command to export real data from the `LearningPackage` model instead of using stub values.
Example of the content:

feat: export LearningPackage data in lp_dump command

---

openedx_learning/apps/authoring/backup_restore/toml.py
openedx_learning/apps/authoring/backup_restore/zipper.py
openedx_learning/apps/authoring/publishing/api.py
tests/openedx_learning/apps/authoring/publishing/test_api.py

**Resolves** [openedx-learning#345](https://github.com/openedx/openedx-learning/issues/345)
- Retrieve data from `PublishableEntity` and `PublishableEntityVersion` instances instead of relying on subclasses like `Component`.
- Introduce a `get_entities` function to handle entity retrieval.

feat: pull entity data from PublishableEntity instances

---

openedx_learning/__init__.py
openedx_learning/apps/authoring/publishing/api.py
openedx_learning/apps/authoring/sections/api.py
openedx_learning/apps/authoring/subsections/api.py
openedx_learning/apps/authoring/units/api.py
tests/openedx_learning/apps/authoring/sections/test_api.py
tests/openedx_learning/apps/authoring/subsections/test_api.py
tests/openedx_learning/apps/authoring/units/test_api.py

Improves performance when fetching lots of container children / parents.
Part of:
* https://github.com/openedx/frontend-app-authoring/issues/1977
* https://github.com/openedx/frontend-app-authoring/issues/1978
Blocks: 
* https://github.com/openedx/edx-platform/pull/36813
Private-ref: [FAL-4178](https://tasks.opencraft.com/browse/FAL-4178)
See https://github.com/openedx/frontend-app-authoring/pull/2186

perf: select related objects in container queries

---

openedx_learning/apps/authoring/backup_restore/zipper.py
tests/openedx_learning/apps/authoring/backup_restore/test_backup.py

Resolves: https://github.com/openedx/openedx-learning/issues/350
This PR implements a new directory layout for component serialization based on:
- **Component namespace**
- **Component type**
- **Component identifier**
---
- Each component is now stored in its own folder hierarchy.
- A TOML file is included for each component, containing its basic metadata.
- If versioned data is available, it is placed under a `component_versions/<version>/` subdirectory inside the component’s folder.
---

feat: serialize components using namespaced directory structure

---

openedx_learning/apps/authoring/backup_restore/zipper.py
tests/openedx_learning/apps/authoring/backup_restore/test_backup.py

Resolves: https://github.com/openedx/openedx-learning/issues/359
This draft PR introduces support for retrieving static files for each component version, ensuring they are correctly generated or fetched when building the `lp_dump` zip file.
- Implements logic to retrieve static files for each component version  
- Defines how static files are named and organized within the archive  
- Cleans up related code for readability and maintainability  
- Adds `prefetch_related` to the content model queries to avoid N+1 issues, along with its corresponding test

feat: get or create static files for each component version in lp_dump file

---

openedx_learning/apps/authoring/backup_restore/toml.py
openedx_learning/apps/authoring/backup_restore/zipper.py
tests/openedx_learning/apps/authoring/backup_restore/test_backup.py

Resolves https://github.com/openedx/openedx-learning/issues/361
This PR adds support for serializing **collections** into the learning package dump file.
- Each collection is serialized as a **TOML file** within the dump folder.  
- Added a `prefetch_related` query on the collections queryset to improve performance.  
- When generating collection TOML files, related **entities** are included, but their **versions** are not.  
Filename: col1_06bb25.toml
```toml
[collection]
title = "Collection 1"
description = "Description of Collection 1"
created = 2025-09-03T18:56:57.524111Z
[[entity]]
uuid = "4ebf2668-75e2-4e27-b339-33b45fd2a087"
can_stand_alone = true
key = "xblock.v1:problem:my_published_example"
[[entity]]
uuid = "a068659e-27ea-4495-82ad-9d0bf11d64da"
can_stand_alone = true
key = …
```

feat: add collection serialization to lp_dump

---

openedx_learning/apps/authoring/backup_restore/toml.py
openedx_learning/apps/authoring/backup_restore/zipper.py
openedx_learning/apps/authoring/publishing/api.py
tests/openedx_learning/apps/authoring/backup_restore/test_backup.py

Resolves: https://github.com/openedx/openedx-learning/issues/374
This PR focuses on testing the backup functionality for a learning package that contains all types of libraries. The goal is to validate the end-to-end dump process and apply any necessary adjustments based on the results.
---
1. Test using **one learning package** that includes all types of libraries.  
2. Upload the resulting test output to this issue.  
3. Apply any required adjustments based on the test results.  
---
---
[Test.zip V1](https://github.com/user-attachments/files/22183960/test.zip)
[Test.zip V2](https://github.com/user-attachments/files/22223816/test.zip)
[Test.zip V3](https://github.com/user-attachments/files/22241622/test.zip)

End-to-End Testing and Adjustments for Backup

---

openedx_learning/apps/authoring/backup_restore/serializers.py
openedx_learning/apps/authoring/backup_restore/toml.py
openedx_learning/apps/authoring/backup_restore/zipper.py

Resolves: https://github.com/openedx/openedx-learning/issues/385 
This PR enables importing collections into Learning Core from the contents of a TOML file.  
This ensures that library structures can be consistently restored from backup definitions.  
[test2.zip](https://github.com/user-attachments/files/22541497/test2.zip)
**Collection**
**Collection entities**

feat: support collection restore in backup/restore process

---

.gitignore
.vscode/launch.json.example
.vscode/settings.json
.vscode/settings.json.example
README.rst

Add example VS Code configuration to automatically detect, run, and debug tests using VS Code's Testing bar. Developers will still need to copy these example files into their own settings in order to make use of them. This was done to avoid potential issues where developer-specific configuration could cause problems for other developers.
Some example screenshots:

test: configure pytest for VS Code
